### ISSUE TITLE
Need better walkthroughs

### ISSUE THREAD

**Issue by rst** [iros/deck.js-codemirror#16]
Hi.  I'm the guy from Ignite yesterday who had glitches setting this project up completely.  (Here's the [presentation](http://www.panix.com/~rst/deck.js/pres/pres0.html) I was using it for; I never quite got the syntax highlighting to work.  The Scala-on-Android framework it describes is [here](https://github.com/rst/positronic_net) if you're curious.)

As I said, I always feel funny about vague bug reports like this; fix it and I definitely owe you lunch...

**Comment by iros** [comment]
It looks like you were missing the right mode file. 
I'm still seeing the javascript.js mode being loaded, and I don't see a scala one.
