### ISSUE TITLE
runnable r code mirror

### ISSUE THREAD

**Issue by lstoetze** [iros/deck.js-codemirror#18]
Dear all,

I discovered this project yesterday. I have to say - I am absolutely fascinated by the possibility to include code mirrors into my presentation and moreover to evaluate them. This is great opportunity for teaching new programming languages to students. 

Here is my question: As I mostly teach R, is there anyway get R codemirrors runnable like in the javascript examples? 

Thank you some much for this great project. 
Best, Lukas

**Comment by iros** [comment]
Unfortunetly we are relying on the browser's ability to evaluate javascript, something that we can't do with R. At some point I will consider adding remote evaluation support, but for now unfortunetly we'll have to stick to this.
