### ISSUE TITLE
html highlighting support

### ISSUE THREAD

**Issue by carpeliam** [iros/deck.js-codemirror#4]
What do you think about adding support for html highlighting? I'm guessing a lot of presentations have some markup to show to go along with JavaScript.

**Comment by iros** [comment]
Done.

commit 742a5e01b05cd64e945b4be266cb2b1d71aee614
Author: Irene Ros irene@bocoup.com
Date:   Tue Sep 13 13:34:13 2011 -0400

```
added html support. Set mode to text/html to get html code highlighting
```

**Comment by carpeliam** [comment]
Sweet! That was fast, thanks.
