### ISSUE TITLE
CoffeeScript highlighting support

### ISSUE THREAD

**Issue by carpeliam** [iros/deck.js-codemirror#5]
This is another language that would be extremely useful for highlighting.

**Comment by carpeliam** [comment]
Probably should have asked for this at the same time I asked for html :/ I remember you originally said that you were trying to keep this small/compressed, I wonder if it'd be worth it to only dynamically discover the modes you need to support at load time, and then require them asynchronously. That way, you only load what you need.

**Comment by iros** [comment]
I will most likely include another folder with all the languages and ask people to include the ones they need. I will also be including the raw CodeMirror code so people can compress it. That will come next release. I'll update this ticket when that's done.

**Comment by iros** [comment]
Added support for highlighting any syntax that codemirror supports in release 0.0.2.
