### ISSUE TITLE
'>' getting translated to '&gt;', etc

### ISSUE THREAD

**Issue by carpeliam** [iros/deck.js-codemirror#6]
My JS/CoffeeScript slides have some special characters that are getting translated into their corresponding html entities. You can see an example on the 8th or so slide on http://carpeliam.github.com/kriegspieljs/lightning/ : "constructor: (@options = {}) -&amp;gt;" etc. This is happening in both CoffeeScript and JavaScript mode. I'm using 0.2, but I saw this in 0.1 too.

**Comment by iros** [comment]
Can you try this in just codemirror and let me know if you see the same issue?

**Comment by iros** [comment]
If you include your code inside of a Textarea versus just a div, it should fix this issue.
